sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - python-dev
      - python-pygments
before_install:
    - sudo pip install future --upgrade
install:
    - sudo python setup.py install
script:
    - doconce --version
    - doconce
notifications:
  email: false
